services:
  - type: web
    name: rag-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free
